### PR TITLE
 Issue #510: Add matrix to test different script code generations

### PR DESCRIPTION
**Pull request by hs-apotell**
Issue #510: Add matrix to test different script code generations

Updated the workflow to build using both tcl and python generators.

Also, fixing broken build.

### CODE REVIEW

**Comment by hzeller** [comment]
It looks like the CMake didn't pick up to run the Python generation environment variable yet - we see the same Tcl log message when generating the code:
https://github.com/chipsalliance/UHDM/pull/513/checks?check_run_id=3666550713#step:7:186

**Comment by hzeller** [comment]
Thanks for working on this!

**Comment by hs-apotell** [comment]
> CMake didn't pick up to run the Python generation environment variable

I thought CMake picks up environment variables automatically. I was wrong. Updated the CMakeLists.txt to compensate for it.

**Review by hzeller — APPROVED** [review]
LGTM

**Pull request merged**
