### PR TITLE
Transitive Grouping

### PR DESCRIPTION
**Pull request by hs-apotell**
Transitive Grouping

Implement transitive grouping in python and also simplify the logic
in tcl script.

### CODE REVIEW

**Comment by hs-apotell** [comment]
@alaindargelas Please review the tcl specific changes before merging.

**Comment by alaindargelas** [comment]
@hs-apotell, please submit a PR where the Python code generation becomes the only generation. Leave the Tcl code for reference, but it should not be called from cmake anymore. We can remove the Surelog matrix CI for Tcl too.

**Comment by hs-apotell** [comment]
@alaindargelas Is this transition only for UHDM or include Surelog as well?

**Comment by alaindargelas** [comment]
For both.

**Pull request merged**
