### PR TITLE
Put all generated code in the build/ directory.

### PR DESCRIPTION
**Pull request by hzeller**
That way, the toplevel source is not clobbered with build
artifacts and it is possible to make a hermetic build.

Issues #484
Signed-off-by: Henner Zeller <hzeller@google.com>

### CODE REVIEW

**Comment by hzeller** [comment]
This build cleanup is also a preparation to work on #484 and #483

**Comment by hzeller** [comment]
The bulk of the preparation work for this change here was in #423

**Comment by hzeller** [comment]
Looks like the msys2 build is failing due to some unrelated reason: compiler runs out of memory. Maybe because it needs to keep track of slightly longer pathes ?

Anyway, addressing the `Serializer_save.cpp` to be less intense on the compiler is a pull request for another time.

**Comment by alaindargelas** [comment]
I'm getting this error pretty consistently after merging this:

[ 59%] Building CXX object third_party/UHDM/CMakeFiles/uhdm.dir/src/UHDM.capnp.c++.o
c++: error: /home/alain/Surelog/build/third_party/UHDM/src/UHDM.capnp.c++: No such file or directory
c++: fatal error: no input files
compilation terminated.



The only way to get rid of it is to remove the UHDM dir and recheckout

**Comment by hzeller** [comment]
You're not supposed to put this in Surelog yet, I'll do that in a separate PR. This will not work yet the way Surelog accesses these.

**Comment by hzeller** [comment]
Arrg, don't roll back, I have more to come.

**Comment by alaindargelas** [comment]
Please resubmit (With a note - DO NOT MERGE IN SURELOG YET) :-)

**Pull request merged**
